export const PARCEL_LABEL_MAP = {
  'Background': 'Background',
  '7Networks_LH_Vis_1': 'L Primary Visual Cortex (V1)',
  '7Networks_LH_Vis_2': 'L Early Visual Cortex (V2)',
  '7Networks_LH_Vis_3': 'L Extrastriate Visual (V3)',
  '7Networks_LH_Vis_4': 'L Extrastriate Visual (V4)',
  '7Networks_LH_Vis_5': 'L Lateral Occipital Cortex 1',
  '7Networks_LH_Vis_6': 'L Lateral Occipital Cortex 2',
  '7Networks_LH_Vis_7': 'L Lingual / Fusiform Gyrus',
  '7Networks_LH_Vis_8': 'L Cuneus',
  '7Networks_LH_Vis_9': 'L Pericalcarine Cortex',
  '7Networks_LH_SomMot_1': 'L Primary Motor Cortex (M1)',
  '7Networks_LH_SomMot_2': 'L Primary Somatosensory Cortex (S1)',
  '7Networks_LH_SomMot_3': 'L Secondary Somatosensory Cortex',
  '7Networks_LH_SomMot_4': 'L Supplementary Motor Area',
  '7Networks_LH_SomMot_5': 'L Premotor Cortex',
  '7Networks_LH_SomMot_6': 'L Superior Temporal Gyrus (auditory)',
  '7Networks_LH_DorsAttn_Post_1': 'L Intraparietal Sulcus 1',
  '7Networks_LH_DorsAttn_Post_2': 'L Intraparietal Sulcus 2',
  '7Networks_LH_DorsAttn_Post_3': 'L Posterior Parietal Cortex 1',
  '7Networks_LH_DorsAttn_Post_4': 'L Posterior Parietal Cortex 2',
  '7Networks_LH_DorsAttn_Post_5': 'L Superior Parietal Lobule',
  '7Networks_LH_DorsAttn_Post_6': 'L Middle Temporal / MT+',
  '7Networks_LH_DorsAttn_PrCv_1': 'L Precuneus (Dorsal Attention)',
  '7Networks_LH_DorsAttn_FEF_1': 'L Frontal Eye Field',
  '7Networks_LH_SalVentAttn_ParOper_1': 'L Parietal Operculum',
  '7Networks_LH_SalVentAttn_FrOperIns_1': 'L Anterior Insula 1',
  '7Networks_LH_SalVentAttn_FrOperIns_2': 'L Anterior Insula 2',
  '7Networks_LH_SalVentAttn_PFCl_1': 'L Inferior Frontal Gyrus (Salience)',
  '7Networks_LH_SalVentAttn_Med_1': 'L dACC / Midcingulate 1',
  '7Networks_LH_SalVentAttn_Med_2': 'L dACC / Midcingulate 2',
  '7Networks_LH_SalVentAttn_Med_3': 'L dACC / Midcingulate 3',
  '7Networks_LH_Limbic_OFC_1': 'L Orbitofrontal Cortex',
  '7Networks_LH_Limbic_TempPole_1': 'L Temporal Pole 1',
  '7Networks_LH_Limbic_TempPole_2': 'L Temporal Pole 2',
  '7Networks_LH_Cont_Par_1': 'L Inferior Parietal Lobule (FPN)',
  '7Networks_LH_Cont_PFCl_1': 'L Lateral Prefrontal Cortex (FPN)',
  '7Networks_LH_Cont_pCun_1': 'L Precuneus (FPN)',
  '7Networks_LH_Cont_Cing_1': 'L Posterior Cingulate (FPN)',
  '7Networks_LH_Default_Temp_1': 'L Middle Temporal Gyrus 1',
  '7Networks_LH_Default_Temp_2': 'L Middle Temporal Gyrus 2',
  '7Networks_LH_Default_Par_1': 'L Angular Gyrus 1',
  '7Networks_LH_Default_Par_2': 'L Angular Gyrus 2',
  '7Networks_LH_Default_PFC_1': 'L Medial Prefrontal Cortex 1',
  '7Networks_LH_Default_PFC_2': 'L Medial Prefrontal Cortex 2',
  '7Networks_LH_Default_PFC_3': 'L Medial Prefrontal Cortex 3',
  '7Networks_LH_Default_PFC_4': 'L Rostral ACC / vmPFC',
  '7Networks_LH_Default_PFC_5': 'L Lateral Prefrontal Cortex (DMN) 1',
  '7Networks_LH_Default_PFC_6': 'L Lateral Prefrontal Cortex (DMN) 2',
  '7Networks_LH_Default_PFC_7': 'L Lateral Prefrontal Cortex (DMN) 3',
  '7Networks_LH_Default_pCunPCC_1': 'L Precuneus / PCC 1',
  '7Networks_LH_Default_pCunPCC_2': 'L Precuneus / PCC 2',
  '7Networks_RH_Vis_1': 'R Primary Visual Cortex (V1)',
  '7Networks_RH_Vis_2': 'R Early Visual Cortex (V2)',
  '7Networks_RH_Vis_3': 'R Extrastriate Visual (V3)',
  '7Networks_RH_Vis_4': 'R Lateral Occipital Cortex 1',
  '7Networks_RH_Vis_5': 'R Lateral Occipital Cortex 2',
  '7Networks_RH_Vis_6': 'R Lingual / Fusiform Gyrus',
  '7Networks_RH_Vis_7': 'R Cuneus',
  '7Networks_RH_Vis_8': 'R Pericalcarine Cortex',
  '7Networks_RH_SomMot_1': 'R Primary Motor Cortex (M1)',
  '7Networks_RH_SomMot_2': 'R Primary Somatosensory Cortex (S1)',
  '7Networks_RH_SomMot_3': 'R Secondary Somatosensory Cortex',
  '7Networks_RH_SomMot_4': 'R Supplementary Motor Area',
  '7Networks_RH_SomMot_5': 'R Premotor Cortex 1',
  '7Networks_RH_SomMot_6': 'R Premotor Cortex 2',
  '7Networks_RH_SomMot_7': 'R Superior Temporal Gyrus (auditory) 1',
  '7Networks_RH_SomMot_8': 'R Superior Temporal Gyrus (auditory) 2',
  '7Networks_RH_DorsAttn_Post_1': 'R Intraparietal Sulcus 1',
  '7Networks_RH_DorsAttn_Post_2': 'R Intraparietal Sulcus 2',
  '7Networks_RH_DorsAttn_Post_3': 'R Posterior Parietal Cortex 1',
  '7Networks_RH_DorsAttn_Post_4': 'R Posterior Parietal Cortex 2',
  '7Networks_RH_DorsAttn_Post_5': 'R Superior Parietal Lobule',
  '7Networks_RH_DorsAttn_PrCv_1': 'R Precuneus (Dorsal Attention)',
  '7Networks_RH_DorsAttn_FEF_1': 'R Frontal Eye Field',
  '7Networks_RH_SalVentAttn_TempOccPar_1': 'R Temporoparietal Junction 1',
  '7Networks_RH_SalVentAttn_TempOccPar_2': 'R Temporoparietal Junction 2',
  '7Networks_RH_SalVentAttn_FrOperIns_1': 'R Anterior Insula',
  '7Networks_RH_SalVentAttn_Med_1': 'R dACC / Midcingulate 1',
  '7Networks_RH_SalVentAttn_Med_2': 'R dACC / Midcingulate 2',
  '7Networks_RH_Limbic_OFC_1': 'R Orbitofrontal Cortex',
  '7Networks_RH_Limbic_TempPole_1': 'R Temporal Pole',
  '7Networks_RH_Cont_Par_1': 'R Inferior Parietal Lobule (FPN) 1',
  '7Networks_RH_Cont_Par_2': 'R Inferior Parietal Lobule (FPN) 2',
  '7Networks_RH_Cont_PFCl_1': 'R Lateral Prefrontal Cortex (FPN) 1',
  '7Networks_RH_Cont_PFCl_2': 'R Lateral Prefrontal Cortex (FPN) 2',
  '7Networks_RH_Cont_PFCl_3': 'R Lateral Prefrontal Cortex (FPN) 3',
  '7Networks_RH_Cont_PFCl_4': 'R Lateral Prefrontal Cortex (FPN) 4',
  '7Networks_RH_Cont_Cing_1': 'R Posterior Cingulate (FPN)',
  '7Networks_RH_Cont_PFCmp_1': 'R Medial-Posterior Prefrontal Cortex',
  '7Networks_RH_Cont_pCun_1': 'R Precuneus (FPN)',
  '7Networks_RH_Default_Par_1': 'R Angular Gyrus',
  '7Networks_RH_Default_Temp_1': 'R Middle Temporal Gyrus 1',
  '7Networks_RH_Default_Temp_2': 'R Middle Temporal Gyrus 2',
  '7Networks_RH_Default_Temp_3': 'R Middle Temporal Gyrus 3',
  '7Networks_RH_Default_PFCv_1': 'R Ventromedial Prefrontal Cortex 1',
  '7Networks_RH_Default_PFCv_2': 'R Ventromedial Prefrontal Cortex 2',
  '7Networks_RH_Default_PFCdPFCm_1': 'R Dorsomedial Prefrontal Cortex 1',
  '7Networks_RH_Default_PFCdPFCm_2': 'R Dorsomedial Prefrontal Cortex 2',
  '7Networks_RH_Default_PFCdPFCm_3': 'R Dorsomedial Prefrontal Cortex 3',
  '7Networks_RH_Default_pCunPCC_1': 'R Precuneus / PCC',
  'HIP-rh': 'R Hippocampus',
  'AMY-rh': 'R Amygdala',
  'pTHA-rh': 'R Posterior Thalamus',
  'aTHA-rh': 'R Anterior Thalamus',
  'NAc-rh': 'R Nucleus Accumbens',
  'GP-rh': 'R Globus Pallidus',
  'PUT-rh': 'R Putamen',
  'CAU-rh': 'R Caudate Nucleus',
  'HIP-lh': 'L Hippocampus',
  'AMY-lh': 'L Amygdala',
  'pTHA-lh': 'L Posterior Thalamus',
  'aTHA-lh': 'L Anterior Thalamus',
  'NAc-lh': 'L Nucleus Accumbens',
  'GP-lh': 'L Globus Pallidus',
  'PUT-lh': 'L Putamen',
  'CAU-lh': 'L Caudate Nucleus',
};

export function getParcelLabel(parcel) {
  return parcel.label ?? PARCEL_LABEL_MAP[parcel.name] ?? parcel.name;
}
